### ISSUE TITLE
3- Header

### ISSUE THREAD

**Issue by NimaHBB** [NimaHBB/capstone-project#2]
## Value statement - a requirement, not a solution
As a Developer i want create Js Functions and basic CSS files.

## Description (Text, Scribble, Wireframe, Design)
This task will done after HTML and Body tags and first project's requirements.

## Acceptance criteria
- [x] Logo
- [x] Main Menu section
- [x] Main menu items Home,Categories,About, Login, user Dashboard menu (Profile, Bookmaks, Orders)
- [x] Search box

## Tasks
- [x] create function and html tags for menu 
- [ ] #10
- [ ] #11
- [x] adjust css for Header
- [x] add Logo and its style
- [x] add search box
- [ ] #9

## Size
Large
