### ISSUE TITLE
4- Footer

### ISSUE THREAD

**Issue by NimaHBB** [NimaHBB/capstone-project#4]
## Value statement - a requirement, not a solution
As a Developer i want to develop a Footer so that to be added in every page.

## Acceptance criteria
- [x] Home Button
- [x] Categories Button
- [x] Basket Button
- [x] Bookmarks Button
- [x] User Account Button

## Tasks
- [x] Adjust footer style
- [x] Create image files for Buttons
- [x] Create List of Buttons
- [ ] #8

## Size
Medium
