### ISSUE TITLE
1- Categories section

### ISSUE THREAD

**Issue by NimaHBB** [NimaHBB/capstone-project#6]
## Value statement - a requirement, not a solution
As a user i need to see categories list wit their icons at first page when i open the app

## Description (Text, Scribble, Wireframe, Design)
- categories must be at the top of other sections after Header and maybe Offers
![categories image](https://user-images.githubusercontent.com/72543010/165534097-d64b3a68-ea78-49e6-a986-d2f04e38d5a5.png)
## Acceptance criteria

- [x] When page loads , app connects to API to get datas.
- [x] After getting datas these items are needed from response data to fill in each category card:
1. - [x] category ID 
2. - [x] Category Name
3. - [x] Category Image 

## Tasks
- [x] Create Schema for Categories
- [x] Create Database
- [x] Create Category Document with datas
- [x] Create API Connection

## Size
Large
