### ISSUE TITLE
Product details

### ISSUE THREAD

**Issue by NimaHBB** [NimaHBB/capstone-project#7]
## Value statement - a requirement, not a solution
As a user i need a page to show every detail of products.
At first page or any other category list that can be used.

## Acceptance criteria
- [ ] Images of Products with zoom possibility
- [ ] Product's Name
- [ ] Price: Previous and current (if there is an offer for that)
- [ ] Add to basket button
- [ ] Add to favourites button
- [ ] Products Comparing Button
- [ ] Product Availability Status
- [ ] Technical Details
- [ ] Show the full root (products > Electronics > Mobiles > Smartphone > Apple)
- [ ] Users Review panel
- [ ] Ranking Bar (according to reviews)

## Tasks
- [ ] Create Detail Page
- [ ] Create Img
- [ ] Create H3 or H4 for title
- [ ] Create P Tag for Prices
- [ ] A button for basket using component
- [ ] A button for favourite using same Button component
- [ ] Create button for comparing products
- [ ] Create a icon or div for availability status
- [ ] Create Technical details Section
- [ ] Create a function to show root of product
- [ ] Create a div for users reviews
- [ ] Adding icons to show ranking 

## Size
Large
